name: Friday Chart Update

on:
  schedule:
    # Runs at 12:01 AM EST every Friday
    - cron: '0 5 * * 5'  # 5 AM UTC = 12 AM EST
  workflow_dispatch:

env:
  TZ: 'America/New_York'

jobs:
  update-data:
    name: Update Chart Data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Debug - Initial state
      run: |
        echo "Initial directory:"
        pwd
        echo "Initial directory contents:"
        ls -la
        echo "Current time:"
        date
        echo "Current timezone:"
        date +"%Z %z"
    
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Debug - After checkout
      run: |
        echo "After checkout directory:"
        pwd
        echo "After checkout directory contents:"
        ls -la
        echo "Checking for package.json:"
        find . -name "package.json"
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        echo "Current directory before npm install:"
        pwd
        echo "Directory contents before npm install:"
        ls -la
        if [ -f "package.json" ]; then
          echo "package.json exists"
          cat package.json
        else
          echo "package.json not found"
          exit 1
        fi
        npm install
    
    - name: Run update script
      run: node scripts/updateData.js
      env:
        APP_ID: ${{ secrets.APP_ID }}
        API_KEY: ${{ secrets.API_KEY }}
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    
    - name: Commit and push if changed
      run: |
        git add data.js
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update chart data [skip ci]" && git push) 