name: Update Chart Data

on:
  schedule:
    # Runs at 12:01 AM EST every Friday
    # Using UTC time (EST is UTC-5)
    - cron: '1 5 * * 5'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for proper versioning
    
    - name: Debug - List files
      run: |
        pwd
        ls -la
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cat package.json
        npm install
    
    - name: Run update script
      run: node scripts/updateData.js
      env:
        APP_ID: ${{ secrets.APP_ID }}
        API_KEY: ${{ secrets.API_KEY }}
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    
    - name: Commit and push if changed
      run: |
        git add data.js
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update chart data [skip ci]" && git push) 